## **Linear Algebra**  

### **Key Concepts**
- **Vectors & Matrices**: Addition, Multiplication, Transpose  
- **Determinant & Inverse**: Singular matrices, Determinant rules  
- **Eigenvalues & Eigenvectors**: Spectral decomposition, PCA  
- **Matrix Factorization**: SVD (Singular Value Decomposition), QR decomposition  

### **Important Formulas**
- **Dot Product**:  
  $$
  \mathbf{a} \cdot \mathbf{b} = \sum a_i b_i
  $$
- **Matrix Multiplication**:  
  $$
  (AB)_{ij} = \sum_{k} A_{ik} B_{kj}
  $$
- **Determinant of a 2×2 Matrix**:  
  $$
  \det \begin{bmatrix} a & b \\ c & d \end{bmatrix} = ad - bc
  $$
- **Eigenvalue Equation**:  
  $$
  Ax = \lambda x
  $$
  where $ \lambda $ are eigenvalues, and $ x $ are eigenvectors.  

### **Sample Questions**
1. What is the **geometric interpretation** of eigenvectors?  
2. If **A is a 3×3 matrix** with determinant = 0, what can you say about its invertibility?  
3. Compute the eigenvalues of  
   $$
   A = \begin{bmatrix} 4 & 2 \\ 1 & 3 \end{bmatrix}
   $$  
4. Explain how **PCA (Principal Component Analysis)** uses eigenvalues and eigenvectors.  




## **Linear Algebra for Data Science Interviews**  

### **1️⃣ Basics of Vectors and Matrices**  
- Definition of Vectors and Matrices  
- Vector Operations: Addition, Subtraction, Scalar Multiplication  
- Matrix Operations: Addition, Multiplication, Transpose  
- Dot Product & Cross Product  

### **2️⃣ Properties of Matrices**  
- Identity Matrix & Zero Matrix  
- Diagonal, Symmetric, and Orthogonal Matrices  
- Rank of a Matrix  
- Trace of a Matrix  

### **3️⃣ Determinant & Inverse of a Matrix**  
- Determinant of a Matrix (2×2, 3×3, n×n)  
- Properties of Determinants  
- Singular vs. Non-Singular Matrices  
- Inverse of a Matrix & Conditions for Invertibility  

### **4️⃣ Eigenvalues & Eigenvectors**  
- Definition and Interpretation  
- Characteristic Equation  
- Spectral Decomposition  
- Diagonalization of Matrices  

### **5️⃣ Matrix Factorization Techniques**  
- **Singular Value Decomposition (SVD)**  
- **QR Decomposition**  
- **LU Decomposition**  

### **6️⃣ Applications in Data Science & Machine Learning**  
- **Principal Component Analysis (PCA)** – How it uses Eigenvalues & Eigenvectors  
- **Dimensionality Reduction** – Role of Matrix Factorization  
- **Linear Regression** – Normal Equations & Least Squares Solution  
- **Neural Networks** – Role of Matrices in Weights & Activations  
- **Recommendation Systems** – Matrix Factorization in Collaborative Filtering  

### **7️⃣ Special Concepts & Theorems**  
- Cramer’s Rule  
- Rank-Nullity Theorem  
- Moore-Penrose Pseudoinverse  
- Frobenius Norm & Spectral Norm  

Do you want to dive into each section in this order, or should we start with a specific topic? 🚀

---

## **1️⃣ Basics of Vectors and Matrices**  

### **1.1 Vectors**  
A **vector** is an ordered list of numbers. It can be represented as:  
$$
\mathbf{v} = \begin{bmatrix} v_1 \\ v_2 \\ v_3 \end{bmatrix}
$$
where $ v_1, v_2, v_3 $ are elements of the vector.  

#### **Operations on Vectors**  
1. **Vector Addition & Subtraction**  
   - Two vectors of the same dimension can be added or subtracted element-wise.

2. **Scalar Multiplication**  
   - Multiplying a vector by a scalar scales each element.

3. **Dot Product**  
   - The **dot product** of two vectors $ \mathbf{a} $ and $ \mathbf{b} $ is given by:  
     $$
     \mathbf{a} \cdot \mathbf{b} = \sum a_i b_i
     $$

### **Python Example**


In [1]:

import numpy as np

# Define vectors
v1 = np.array([2, 3, 4])
v2 = np.array([1, 0, -1])

# Vector addition
add_result = v1 + v2

# Scalar multiplication
scalar_mult = 3 * v1

# Dot product
dot_product = np.dot(v1, v2)

print("Vector Addition:", add_result)
print("Scalar Multiplication:", scalar_mult)
print("Dot Product:", dot_product)


Vector Addition: [3 3 3]
Scalar Multiplication: [ 6  9 12]
Dot Product: -2




---

### **1.2 Matrices**  
A **matrix** is a 2D array of numbers, represented as:  
$$
A = \begin{bmatrix} 
a_{11} & a_{12} \\ 
a_{21} & a_{22} 
\end{bmatrix}
$$

#### **Operations on Matrices**
1. **Matrix Addition & Subtraction**  
   - Can be performed if both matrices have the same dimensions.
  
2. **Matrix Multiplication**  
   - If $ A $ is an $ m \times n $ matrix and $ B $ is an $ n \times p $ matrix, then $ AB $ results in an $ m \times p $ matrix.
   - Formula:  
     $$
     (AB)_{ij} = \sum_{k} A_{ik} B_{kj}
     $$

3. **Matrix Transpose**  
   - Flips rows into columns:  
     $$
     A^T_{ij} = A_{ji}
     $$

### **Python Example**


In [2]:

# Define matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 3]])

# Matrix addition
add_matrix = A + B

# Matrix multiplication
mult_matrix = np.dot(A, B)  # Or use A @ B

# Transpose of a matrix
transpose_A = A.T

print("Matrix Addition:\n", add_matrix)
print("Matrix Multiplication:\n", mult_matrix)
print("Transpose of A:\n", transpose_A)


Matrix Addition:
 [[3 2]
 [4 7]]
Matrix Multiplication:
 [[ 4  6]
 [10 12]]
Transpose of A:
 [[1 3]
 [2 4]]



---

### **1.3 Special Matrices**  
1. **Identity Matrix ($ I $)**  
   - A square matrix with 1s on the diagonal and 0s elsewhere.
   - Example:
     $$
     I = \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}
     $$

2. **Zero Matrix ($ 0 $)**  
   - A matrix with all elements as 0.

3. **Diagonal Matrix**  
   - A matrix where all non-diagonal elements are zero.

### **Python Example**


In [3]:

# Identity matrix
I = np.eye(3)

# Zero matrix
Z = np.zeros((2, 2))

# Diagonal matrix
D = np.diag([4, 5, 6])

print("Identity Matrix:\n", I)
print("Zero Matrix:\n", Z)
print("Diagonal Matrix:\n", D)


Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Zero Matrix:
 [[0. 0.]
 [0. 0.]]
Diagonal Matrix:
 [[4 0 0]
 [0 5 0]
 [0 0 6]]




---

## **Key Takeaways**
- **Vectors** are 1D arrays, and **matrices** are 2D arrays.  
- **Basic operations** like addition, scalar multiplication, and dot product apply to vectors.  
- **Matrix multiplication** requires conforming dimensions.  
- **Special matrices** like identity, zero, and diagonal have unique properties.

---


### **Dot Product & Cross Product in Linear Algebra**  

Both **dot product** and **cross product** are fundamental operations in vector algebra, widely used in data science, physics, and machine learning.  

---

## **Dot Product (Scalar Product)**
The **dot product** of two vectors $ \mathbf{a} $ and $ \mathbf{b} $ is given by:  
$$
\mathbf{a} \cdot \mathbf{b} = \sum a_i b_i
$$
or in summation notation:  
$$
\mathbf{a} \cdot \mathbf{b} = a_1b_1 + a_2b_2 + \dots + a_n b_n
$$

### **Geometric Interpretation**
- The dot product measures the **similarity** between two vectors.
- If $ \theta $ is the angle between two vectors:
  $$
  \mathbf{a} \cdot \mathbf{b} = ||\mathbf{a}|| ||\mathbf{b}|| \cos\theta
  $$
- **If $ \theta = 90^\circ $ (perpendicular vectors), the dot product is 0** (orthogonal vectors).  
- **If $ \theta = 0^\circ $, the vectors are in the same direction (maximum similarity).**

### **Python Example: Dot Product**


In [4]:

import numpy as np

# Define vectors
a = np.array([2, 3, 4])
b = np.array([1, 0, -1])

# Compute dot product
dot_product = np.dot(a, b)

# Compute angle (cosine similarity)
cos_theta = dot_product / (np.linalg.norm(a) * np.linalg.norm(b))

print("Dot Product:", dot_product)
print("Cosine of Angle:", cos_theta)


Dot Product: -2
Cosine of Angle: -0.2626128657194451



🔹 **Use Case in Data Science**:  
- Used in **cosine similarity** (e.g., text similarity in NLP).  
- Measures how aligned two feature vectors are in ML.

---

## **Cross Product (Vector Product)**
The **cross product** is defined only for **3D vectors** and results in another **vector** perpendicular to both input vectors.  

$$
\mathbf{a} \times \mathbf{b} =
\begin{bmatrix} a_1 \\ a_2 \\ a_3 \end{bmatrix}
\times
\begin{bmatrix} b_1 \\ b_2 \\ b_3 \end{bmatrix}
=
\begin{bmatrix}
a_2 b_3 - a_3 b_2 \\
a_3 b_1 - a_1 b_3 \\
a_1 b_2 - a_2 b_1
\end{bmatrix}
$$

### **Geometric Interpretation**
- The **resulting vector is perpendicular to both $ \mathbf{a} $ and $ \mathbf{b} $**.
- The **magnitude** (length) of the cross product is:
  $$
  ||\mathbf{a} \times \mathbf{b}|| = ||\mathbf{a}|| ||\mathbf{b}|| \sin\theta
  $$
  where $ \theta $ is the angle between $ \mathbf{a} $ and $ \mathbf{b} $.

### **Python Example: Cross Product**


In [6]:

# Define 3D vectors
a = np.array([2, 3, 4])
b = np.array([1, 0, -1])

# Compute cross product
cross_product = np.cross(a, b)

print("Cross Product:", cross_product)


Cross Product: [-3  6 -3]




🔹 **Use Case in Data Science & AI**:  
- Used in **computer graphics & physics simulations**.  
- Helps in **calculating normals** to planes in 3D space.

---

## **Key Differences**
| Feature         | Dot Product | Cross Product |
|----------------|------------|--------------|
| **Result**     | Scalar (number) | Vector |
| **Definition** | $ \sum a_i b_i $ | Determinant formula |
| **Dimension**  | Works for any n-dimensional vectors | Only for 3D vectors |
| **Use Case**   | Similarity measurement, ML, NLP | 3D physics, graphics, robotics |

---


# **2️⃣ Properties of Vectors and Matrices**  

Understanding the **properties of vectors and matrices** is crucial for data science, machine learning, and numerical computing. This section will cover:  

1. **Properties of Vectors**  
2. **Properties of Matrices**  

We'll include **Python examples** to reinforce the concepts.

---

## **Properties of Vectors**  

### **1.1 Vector Addition Properties**  
For any vectors **$ a $** and **$ b $**:  

1. **Commutative Property**:  
   $$
   \mathbf{a} + \mathbf{b} = \mathbf{b} + \mathbf{a}
   $$
   - Order of addition doesn’t matter.

2. **Associative Property**:  
   $$
   (\mathbf{a} + \mathbf{b}) + \mathbf{c} = \mathbf{a} + (\mathbf{b} + \mathbf{c})
   $$
   - Grouping doesn’t affect the result.

3. **Additive Identity**:  
   $$
   \mathbf{a} + \mathbf{0} = \mathbf{a}
   $$
   - Adding the **zero vector** results in the same vector.

4. **Additive Inverse**:  
   $$
   \mathbf{a} + (-\mathbf{a}) = \mathbf{0}
   $$
   - A vector plus its negative results in the **zero vector**.

### **Python Example**


In [ ]:
import numpy as np

a = np.array([2, 3, 4])
b = np.array([1, -1, 2])
zero_vector = np.zeros(3)

# Commutative Property
print("a + b:", a + b)
print("b + a:", b + a)

# Associative Property
c = np.array([-2, 1, 0])
print("(a + b) + c:", (a + b) + c)
print("a + (b + c):", a + (b + c))

# Additive Identity
print("a + zero_vector:", a + zero_vector)

# Additive Inverse
print("a + (-a):", a + (-a))


---

### **1.2 Scalar Multiplication Properties**
For a vector $ \mathbf{a} $ and scalars $ c $ and $ d $:

1. **Distributive Property (Vector Addition)**:  
   $$
   c (\mathbf{a} + \mathbf{b}) = c\mathbf{a} + c\mathbf{b}
   $$
2. **Distributive Property (Scalar Addition)**:  
   $$
   (c + d) \mathbf{a} = c\mathbf{a} + d\mathbf{a}
   $$
3. **Associative Property**:  
   $$
   c (d\mathbf{a}) = (cd)\mathbf{a}
   $$
4. **Multiplicative Identity**:  
   $$
   1\mathbf{a} = \mathbf{a}
   $$

---

## **Properties of Matrices**  

A **matrix** is a rectangular array of numbers arranged in **rows** and **columns**.  

### **2.1 Matrix Addition Properties**  
For matrices $ A, B, C $ of the same size:

1. **Commutative Property**:  
   $$
   A + B = B + A
   $$
2. **Associative Property**:  
   $$
   (A + B) + C = A + (B + C)
   $$
3. **Additive Identity** (Zero Matrix $ 0 $):  
   $$
   A + 0 = A
   $$
4. **Additive Inverse**:  
   $$
   A + (-A) = 0
   $$

### **Python Example**


In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 3], [4, 5]])
zero_matrix = np.zeros((2, 2))

# Commutative Property
print("A + B:\n", A + B)
print("B + A:\n", B + A)

# Associative Property
C = np.array([[5, 6], [7, 8]])
print("(A + B) + C:\n", (A + B) + C)
print("A + (B + C):\n", A + (B + C))

# Additive Identity
print("A + zero_matrix:\n", A + zero_matrix)

# Additive Inverse
print("A + (-A):\n", A + (-A))



---

### **2.2 Matrix Multiplication Properties**  
For matrices $ A, B, C $ where multiplication is defined:

1. **Associative Property**:  
   $$
   (AB)C = A(BC)
   $$
   - Grouping of multiplication does not matter.

2. **Distributive Property**:  
   $$
   A(B + C) = AB + AC
   $$
   - Matrix multiplication distributes over addition.

3. **Multiplicative Identity**:  
   $$
   AI = A
   $$
   - Multiplication with the identity matrix $ I $ returns the same matrix.

4. **Non-Commutativity** (Important!):  
   $$
   AB \neq BA
   $$
   - Unlike scalar multiplication, matrix multiplication is **not** commutative.

### **Python Example**


In [ ]:
I = np.eye(2)  # Identity Matrix
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 3]])

# Associative Property
print("(AB)C:\n", np.dot(np.dot(A, B), I))
print("A(BC):\n", np.dot(A, np.dot(B, I)))

# Distributive Property
C = np.array([[5, 6], [7, 8]])
print("A(B + C):\n", np.dot(A, B + C))
print("AB + AC:\n", np.dot(A, B) + np.dot(A, C))

# Identity Property
print("AI:\n", np.dot(A, I))

# Non-Commutativity
print("AB:\n", np.dot(A, B))
print("BA:\n", np.dot(B, A))  # Will be different from AB




---

### **2.3 Special Matrices**
1. **Identity Matrix $ I $**  
   - A square matrix with **1s on the diagonal** and **0s elsewhere**.  
   - Multiplying any matrix $ A $ with $ I $ gives $ A $.

2. **Zero Matrix $ 0 $**  
   - All elements are zero.
   - Multiplication with any matrix gives a **zero matrix**.

3. **Diagonal Matrix**  
   - Non-zero elements exist only on the diagonal.
   - Example:
     $$
     D = \begin{bmatrix} 3 & 0 \\ 0 & 5 \end{bmatrix}
     $$

4. **Symmetric Matrix**  
   - A matrix $ A $ is symmetric if:
     $$
     A^T = A
     $$
   - Example:
     $$
     \begin{bmatrix} 1 & 2 \\ 2 & 3 \end{bmatrix}
     $$

### **Python Example**


In [ ]:

# Identity Matrix
I = np.eye(3)
print("Identity Matrix:\n", I)

# Zero Matrix
Z = np.zeros((3, 3))
print("Zero Matrix:\n", Z)

# Diagonal Matrix
D = np.diag([3, 5, 7])
print("Diagonal Matrix:\n", D)

# Symmetric Matrix
S = np.array([[1, 2], [2, 3]])
print("Symmetric Matrix:\n", S)
print("Transpose of S:\n", S.T)  # Should be same as S


# **Exploring Orthogonal Matrix, Rank, and Trace of a Matrix**  

These three properties are important in **linear algebra** and have applications in **machine learning, data science, and optimization**. Let's explore them with **definitions, properties, examples, and Python code**.  

---

## **Orthogonal Matrix**  

### **Definition**  
A **square matrix $ A $** is **orthogonal** if its **transpose is equal to its inverse**:  

$$
A^T A = A A^T = I
$$

where:  
- $ A^T $ is the **transpose** of $ A $  
- $ I $ is the **identity matrix**  

### **Properties of Orthogonal Matrices**  
1. **Preserves length (Norm is unchanged)**: $ ||Ax|| = ||x|| $  
2. **Determinant is ±1**: $ \det(A) = \pm 1 $  
3. **Preserves dot product**: $ (Ax) \cdot (Ay) = x \cdot y $  
4. **Inverse is its transpose**: $ A^{-1} = A^T $  

### **Example of an Orthogonal Matrix**
$$
A = \begin{bmatrix} 0 & 1 \\ -1 & 0 \end{bmatrix}
$$
$$
A^T = \begin{bmatrix} 0 & -1 \\ 1 & 0 \end{bmatrix}
$$
$$
A^T A = \begin{bmatrix} 0 & -1 \\ 1 & 0 \end{bmatrix} \cdot \begin{bmatrix} 0 & 1 \\ -1 & 0 \end{bmatrix} = I
$$

---

### **Python Example: Checking Orthogonality**


In [ ]:
import numpy as np

# Define a matrix
A = np.array([[0, 1], [-1, 0]])

# Compute A^T * A
orthogonality_check = np.dot(A.T, A)

# Check if it equals the identity matrix
is_orthogonal = np.allclose(orthogonality_check, np.eye(2))

print("Matrix A:\n", A)
print("A^T * A:\n", orthogonality_check)
print("Is A orthogonal?", is_orthogonal)



---

## **Rank of a Matrix**  

### **Definition**  
The **rank of a matrix** is the **number of linearly independent rows or columns**. It tells us:  
- The **dimensionality** of the column space (range) of the matrix.  
- Whether a system of linear equations has **a unique solution, infinite solutions, or no solution**.  

### **Key Properties**  
1. **$ \text{Rank}(A) \leq \min(m, n) $ for an $ m \times n $ matrix**  
2. **Full rank**:
   - If $ \text{Rank}(A) = n $ (number of columns), it's **full column rank** (invertible if square).  
   - If $ \text{Rank}(A) = m $ (number of rows), it's **full row rank**.  
3. **A singular matrix has rank $ < n $** (not invertible).  

---

### **Example of Rank Calculation**
$$
A = \begin{bmatrix} 1 & 2 \\ 2 & 4 \end{bmatrix}
$$
- **Second row is 2× the first row → Linearly dependent**  
- **Rank(A) = 1 (not full rank)**  

---

### **Python Example: Compute Matrix Rank**


In [ ]:
A = np.array([[1, 2], [2, 4]])
rank_A = np.linalg.matrix_rank(A)

print("Matrix A:\n", A)
print("Rank of A:", rank_A)



---

## **Trace of a Matrix**  

### **Definition**  
The **trace of a square matrix** is the **sum of its diagonal elements**:  

$$
\text{Tr}(A) = \sum_{i} A_{ii}
$$

### **Properties**  
1. **Trace of sum**:  
   $$
   \text{Tr}(A + B) = \text{Tr}(A) + \text{Tr}(B)
   $$
2. **Trace of product (only if order matches)**:  
   $$
   \text{Tr}(AB) = \text{Tr}(BA)
   $$
3. **Trace of identity matrix**:  
   $$
   \text{Tr}(I_n) = n
   $$

---

### **Example of Trace Calculation**
$$
A = \begin{bmatrix} 3 & 5 \\ 1 & 4 \end{bmatrix}
$$
$$
\text{Tr}(A) = 3 + 4 = 7
$$

---

### **Python Example: Compute Matrix Trace**


In [ ]:
A = np.array([[3, 5], [1, 4]])
trace_A = np.trace(A)

print("Matrix A:\n", A)
print("Trace of A:", trace_A)




---

## **Key Takeaways**
- **Vectors** and **matrices** follow commutative, associative, and distributive properties for addition.
- **Matrix multiplication is associative and distributive but NOT commutative**.
- **Special matrices** (identity, zero, diagonal, symmetric) have unique properties useful in ML & AI.

---


# **Determinant and Inverse of a Matrix**  

Determinants and inverses play a crucial role in **linear algebra**, especially in **solving linear systems, transformations, and eigenvalue problems**. Let's explore their **definitions, properties, and Python code implementations**.  

---

## **Determinant of a Matrix**  

### **Definition**  
The **determinant** of a square matrix $ A $ (denoted as $ \det(A) $ or $ |A| $) is a **scalar value** that represents the scaling factor of the linear transformation described by $ A $.  

### **Determinant of a 2×2 Matrix**  
For a $ 2 \times 2 $ matrix:  

$$
A = \begin{bmatrix} a & b \\ c & d \end{bmatrix}
$$

$$
\det(A) = ad - bc
$$

### **Determinant of a 3×3 Matrix**  
For a $ 3 \times 3 $ matrix:  

$$
A = \begin{bmatrix} a & b & c \\ d & e & f \\ g & h & i \end{bmatrix}
$$

$$
\det(A) = a(ei - fh) - b(di - fg) + c(dh - eg)
$$

---

### **Properties of Determinants**  
1. **Determinant of Identity Matrix**: $ \det(I) = 1 $  
2. **Determinant of a Singular Matrix**: If $ \det(A) = 0 $, then $ A $ is **singular** (not invertible).  
3. **Multiplicative Property**: $ \det(AB) = \det(A) \cdot \det(B) $  
4. **Effect of Row Operations**:  
   - Swapping two rows **negates** the determinant.  
   - Multiplying a row by $ k $ **multiplies** the determinant by $ k $.  
   - Adding a multiple of one row to another **does not** change the determinant.  
5. **Determinant of a Transpose**: $ \det(A^T) = \det(A) $  

---

### **Python Code: Computing Determinant**


In [ ]:
import numpy as np

# Define a matrix
A = np.array([[4, 3], [6, 3]])

# Compute determinant
det_A = np.linalg.det(A)

print("Matrix A:\n", A)
print("Determinant of A:", det_A)



---

## **Singular vs. Non-Singular Matrices**  

### **Singular Matrix**  
A matrix $ A $ is **singular** if:  
- $ \det(A) = 0 $  
- It **does not have an inverse**  
- The rows or columns are **linearly dependent**  

Example of a **singular** matrix:  
$$
A = \begin{bmatrix} 2 & 4 \\ 1 & 2 \end{bmatrix}
$$
$$
\det(A) = (2 \times 2) - (4 \times 1) = 4 - 4 = 0
$$
This matrix is singular because the second row is a multiple of the first row.

---

### **Non-Singular Matrix**  
A matrix $ A $ is **non-singular** if:  
- $ \det(A) \neq 0 $  
- It has an **inverse**  
- The rows or columns are **linearly independent**  

Example of a **non-singular** matrix:  
$$
A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}
$$
$$
\det(A) = (1 \times 4) - (2 \times 3) = 4 - 6 = -2
$$

---

### **Python Code: Checking if a Matrix is Singular**


In [ ]:
A = np.array([[2, 4], [1, 2]])

# Compute determinant
det_A = np.linalg.det(A)

# Check if the matrix is singular
if np.isclose(det_A, 0):
    print("Matrix A is singular (not invertible).")
else:
    print("Matrix A is non-singular (invertible).")



---

## **Inverse of a Matrix**  

### **Definition**  
The **inverse of a square matrix $ A $**, denoted as $ A^{-1} $, is the matrix that satisfies:  

$$
A A^{-1} = A^{-1} A = I
$$

where $ I $ is the **identity matrix**.

### **Conditions for Inverse to Exist**  
A matrix $ A $ is **invertible** if and only if:  
- $ \det(A) \neq 0 $ (non-singular)  
- It is a **square matrix** (same number of rows and columns)  

---

### **Formula for the Inverse of a 2×2 Matrix**  
For  
$$
A = \begin{bmatrix} a & b \\ c & d \end{bmatrix}
$$
The inverse is:

$$
A^{-1} = \frac{1}{\det(A)} \begin{bmatrix} d & -b \\ -c & a \end{bmatrix}
$$

**Example:**
$$
A = \begin{bmatrix} 4 & 7 \\ 2 & 6 \end{bmatrix}
$$

$$
\det(A) = (4 \times 6) - (7 \times 2) = 24 - 14 = 10
$$

$$
A^{-1} = \frac{1}{10} \begin{bmatrix} 6 & -7 \\ -2 & 4 \end{bmatrix}
$$

---

### **Python Code: Computing Matrix Inverse**


In [ ]:
# Define a matrix
A = np.array([[4, 7], [2, 6]])

# Compute inverse
A_inv = np.linalg.inv(A)

print("Matrix A:\n", A)
print("Inverse of A:\n", A_inv)



---

### **Properties of Matrix Inverse**  
1. **Inverse of a product**:  
   $$
   (AB)^{-1} = B^{-1} A^{-1}
   $$
2. **Inverse of a transpose**:  
   $$
   (A^T)^{-1} = (A^{-1})^T
   $$
3. **Inverse of an inverse**:  
   $$
   (A^{-1})^{-1} = A
   $$
4. **If $ A $ is orthogonal**:  
   $$
   A^{-1} = A^T
   $$

---

## **Summary Table**  

| Concept | Definition | Condition |
|---------|-----------|-----------|
| **Determinant** | A scalar that measures the transformation scaling of a matrix | $ \det(A) \neq 0 $ for an invertible matrix |
| **Singular Matrix** | A matrix with $ \det(A) = 0 $, meaning it has no inverse | Rows/columns are linearly dependent |
| **Non-Singular Matrix** | A matrix with $ \det(A) \neq 0 $, meaning it has an inverse | Rows/columns are linearly independent |
| **Inverse of a Matrix** | A matrix that satisfies $ A A^{-1} = I $ | Exists only if $ \det(A) \neq 0 $ |

---


# **Eigenvalues and Eigenvectors**  

Eigenvalues and eigenvectors play a crucial role in **machine learning, PCA (Principal Component Analysis), stability analysis, and differential equations**. They help in **understanding linear transformations, dimensionality reduction, and system stability**.  

---

## **What Are Eigenvalues and Eigenvectors?**  

For a **square matrix** $ A $, an **eigenvector** is a **nonzero vector** $ x $ such that multiplying it by $ A $ results in a **scaled version** of itself:  

$$
A x = \lambda x
$$

where:  
- $ x $ is the **eigenvector**  
- $ \lambda $ is the **eigenvalue**  

### **Example Interpretation**  
If $ A $ represents a **transformation (rotation, scaling, etc.)**, then an **eigenvector** is a special direction that **remains unchanged** (except for scaling), and the **eigenvalue** tells how much it is scaled.  

---



## **How to Compute Eigenvalues and Eigenvectors?**  

### **Step 1: Compute Eigenvalues**
Eigenvalues are found by solving the **characteristic equation**:  

$$
\det(A - \lambda I) = 0
$$

where $ I $ is the identity matrix.

For a **2×2 matrix**:  

$$
A = \begin{bmatrix} a & b \\ c & d \end{bmatrix}
$$

$$
\det \begin{bmatrix} a-\lambda & b \\ c & d-\lambda \end{bmatrix} = 0
$$

$$
(a - \lambda)(d - \lambda) - bc = 0
$$

Solving this quadratic equation gives **two eigenvalues**.

---

### **Step 2: Compute Eigenvectors**
For each **eigenvalue $ \lambda $**, solve:  

$$
(A - \lambda I) x = 0
$$

This system of equations gives the eigenvector(s) corresponding to $ \lambda $.

---



## **Example Calculation (2×2 Matrix)**  

### **Matrix:**
$$
A = \begin{bmatrix} 4 & 2 \\ 1 & 3 \end{bmatrix}
$$

### **Step 1: Compute Eigenvalues**  
$$
\det(A - \lambda I) = \det \begin{bmatrix} 4 - \lambda & 2 \\ 1 & 3 - \lambda \end{bmatrix} = 0
$$

$$
(4 - \lambda)(3 - \lambda) - (2 \times 1) = 0
$$

$$
(4 - \lambda)(3 - \lambda) - 2 = 0
$$

$$
12 - 4\lambda - 3\lambda + \lambda^2 - 2 = 0
$$

$$
\lambda^2 - 7\lambda + 10 = 0
$$

Solving $ (\lambda - 5)(\lambda - 2) = 0 $, we get:

$$
\lambda_1 = 5, \quad \lambda_2 = 2
$$

### **Step 2: Compute Eigenvectors**  
For **$ \lambda_1 = 5 $**:  
Solve:  
$$
\begin{bmatrix} 4-5 & 2 \\ 1 & 3-5 \end{bmatrix} \begin{bmatrix} x_1 \\ x_2 \end{bmatrix} = 0
$$

$$
\begin{bmatrix} -1 & 2 \\ 1 & -2 \end{bmatrix} \begin{bmatrix} x_1 \\ x_2 \end{bmatrix} = 0
$$

From **row 1**: $ -x_1 + 2x_2 = 0 $ → $ x_1 = 2x_2 $  

Eigenvector:  
$$
x = \begin{bmatrix} 2 \\ 1 \end{bmatrix}
$$

For **$ \lambda_2 = 2 $**:  
Solve:  
$$
\begin{bmatrix} 4-2 & 2 \\ 1 & 3-2 \end{bmatrix} \begin{bmatrix} x_1 \\ x_2 \end{bmatrix} = 0
$$

$$
\begin{bmatrix} 2 & 2 \\ 1 & 1 \end{bmatrix} \begin{bmatrix} x_1 \\ x_2 \end{bmatrix} = 0
$$

From **row 1**: $ 2x_1 + 2x_2 = 0 $ → $ x_1 = -x_2 $  

Eigenvector:  
$$
x = \begin{bmatrix} -1 \\ 1 \end{bmatrix}
$$

---

## **Python Code to Compute Eigenvalues & Eigenvectors**


In [7]:
import numpy as np

# Define matrix A
A = np.array([[4, 2], [1, 3]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Matrix A:\n", A)
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Matrix A:
 [[4 2]
 [1 3]]
Eigenvalues:
 [5. 2.]
Eigenvectors:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]



## **Properties of Eigenvalues and Eigenvectors**  

1. **Sum of Eigenvalues = Trace of Matrix**  
   $$
   \sum \lambda_i = \text{trace}(A) = \sum A_{ii}
   $$

2. **Product of Eigenvalues = Determinant of Matrix**  
   $$
   \prod \lambda_i = \det(A)
   $$

3. **Eigenvalues of a Diagonal Matrix**  
   If $ A $ is diagonal:  
   $$
   A = \begin{bmatrix} \lambda_1 & 0 \\ 0 & \lambda_2 \end{bmatrix}
   $$
   then its eigenvalues are $ \lambda_1, \lambda_2 $.

4. **Eigenvectors of a Symmetric Matrix Are Orthogonal**  
   If $ A $ is symmetric ($ A^T = A $), then eigenvectors corresponding to different eigenvalues are **orthogonal**.

---



## **Applications in Data Science**  

### **1. Principal Component Analysis (PCA)**
- PCA uses **eigenvalues and eigenvectors** of the **covariance matrix** to identify the most important directions (principal components) in data.

### **2. Google's PageRank Algorithm**
- The importance of web pages is determined using **eigenvectors** of a transition probability matrix.

### **3. Stability of Dynamical Systems**
- Eigenvalues help determine **stability**:  
  - If all eigenvalues have **negative real parts**, the system is **stable**.  
  - If any eigenvalue has a **positive real part**, the system is **unstable**.

---



## **Summary Table**  

| Concept | Definition |
|---------|-----------|
| **Eigenvalue** $ \lambda $ | Scalar that scales the eigenvector during transformation |
| **Eigenvector** $ x $ | Nonzero vector that remains in the same direction after transformation |
| **Characteristic Equation** | $ \det(A - \lambda I) = 0 $ |
| **Trace Property** | $ \sum \lambda_i = \text{trace}(A) $ |
| **Determinant Property** | $ \prod \lambda_i = \det(A) $ |
| **Eigenvectors of Symmetric Matrices** | Orthogonal |

---
